/**********************************************************************************
 * Simple tool to verify the signature of a given binary
 *
 * Copyright (C) 2004 Joe Fox All rights reserved.
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *********************************************************************************/

#include <iostream>

#include "pubkey.h" // for szKeyBuf (generated by "genkeypr pub <pubkeyfile>")
#include "signelf.h"

int main(int argc, char **argv)
{
	// verify the lib using key in szKeyBuf
	bool bVerify = signelf::verifyLib(szKeyBuf, sizeof(szKeyBuf), argv[1]);
	std::cout << "Result: " << bVerify << std::endl;;

	return bVerify ? 0 : 1;
}

